---
# Global vars for deployment
stack_dest: /opt/cieplarnia
web_next_public_api_base_url: "http://10.252.249.2:8000"
web_public_origin: "http://10.252.249.2:3000"
agg_allowed_origins: "{{ web_public_origin }},http://localhost:3000,http://web:3000"
mosquitto_users:
  - name: aggregator
    password: "agregator123"
  - name: dashboard
    password: "dashboard123"
mosquitto_enable_tls: false
mosquitto_ca_subject: "/C=PL/ST=Mazowieckie/L=Warsaw/O=Cieplarnia/OU=IoT/CN=cieplarnia-ca"
mosquitto_cert_subject: "/C=PL/ST=Mazowieckie/L=Warsaw/O=Cieplarnia/OU=IoT/CN=mosquitto-broker"
mosquitto_cert_sans: "DNS:mosquitto.local,IP:127.0.0.1"
